import { COLORS } from "@/constants/theme";
import { Dimensions, StyleSheet } from "react-native";

const { width: SCREEN_WIDTH } = Dimensions.get("window");

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#000",
        paddingTop: 20,
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 20,
        position: "relative",
    },
    titleContainer: {
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
    },
    backButton: {
        width: 40,
        height: 40,
        position: "absolute",
        left: 16,
        zIndex: 2,
        justifyContent: "center",
        alignItems: "center",
    },
    title: {
        color: COLORS.white,
        fontSize: 22,
        fontWeight: "700",
    },
    subtitle: {
        color: COLORS.grey,
        fontSize: 14,
        fontWeight: "500",
        marginTop: 2,
    },
    modalContainer: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.6)",
        justifyContent: "center",
        alignItems: "center",
    },
    scrollContainer: {
        flexGrow: 1,
        justifyContent: "center",
        alignItems: "center",
        paddingVertical: 40,
        width: "100%",
    },
    modalContent: {
        backgroundColor: "#1C1C1E",
        padding: 20,
        borderRadius: 16,
        width: SCREEN_WIDTH * 0.85,
        alignSelf: "center",
        elevation: 6,
        shadowColor: "#000",
        shadowOpacity: 0.3,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 3 },
    },
    modalTitle: {
        color: "white",
        fontSize: 18,
        fontWeight: "bold",
        marginBottom: 16,
        textAlign: "center",
    },
    input: {
        backgroundColor: "#2C2C2E",
        color: "white",
        borderRadius: 10,
        padding: 10,
        marginBottom: 12,
    },
    saveButton: {
        backgroundColor: "#4ADE80",
        borderRadius: 10,
        padding: 14,
        justifyContent: "center",
        alignItems: "center",
        marginTop: 8,
    },
    deleteButton: {
        backgroundColor: "#e62828be",
        borderRadius: 10,
        padding: 14,
        justifyContent: "center",
        alignItems: "center",
        marginTop: 8,
    },
    cancelButton: {
        backgroundColor: "#2A2A2A",
        borderRadius: 10,
        padding: 14,
        justifyContent: "center",
        alignItems: "center",
        marginTop: 8,
    },
    buttonText: {
        color: "black",
        fontWeight: "bold",
    },
    cancelText: {
        color: "#aaa",
        textAlign: "center",
    },
    loaderContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "rgba(0,0,0,0.6)",
    },
    loaderGif: {
        width: 120,
        height: 120,
        borderRadius: 30,
    },
    modalSubtitle: {
        color: "white",
        marginBottom: 7,
    },
    modalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 10,
    },
    legendContainer: {
        marginTop: 20,
        alignItems: "center",
        justifyContent: "center",
        width: "100%",
        paddingHorizontal: 16,
    },
    legendRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "flex-start",
        width: "80%",
        marginVertical: 4,
        gap: 8,
    },
    legendColorBox: {
        height: 14,
        width: 14,
        borderRadius: 3,
        marginRight: 10,
    },
    legendText: {
        color: COLORS.white,
        fontSize: 14,
        lineHeight: 18,
        textAlignVertical: "center",
    },
    attendanceMessageContainer: {
        marginTop: 16,
        alignItems: "center",
        paddingHorizontal: 16,
        justifyContent: "center",
    },
    attendanceMessageText: {
        fontSize: 15,
        fontWeight: "600",
        textAlign: "center",
    },
});